services:
  - type: web
    name: cuhp-ctf-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000
      - key: CORS_ORIGIN
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: EMAIL_VERIFICATION_URL
        sync: false
      - key: EMAILJS_SERVICE_ID
        sync: false
      - key: EMAILJS_TEMPLATE_ID
        sync: false
      - key: EMAILJS_PUBLIC_KEY
        sync: false
      - key: EMAILJS_PRIVATE_KEY
        sync: false
