services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: cuhp-ctf-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://bharwal710_db_user:V4vTRQabOsDCwRwV@ac-sfmhesd-shard-00-00.4beckzr.mongodb.net:27017,ac-sfmhesd-shard-00-01.4beckzr.mongodb.net:27017,ac-sfmhesd-shard-00-02.4beckzr.mongodb.net:27017/cuhp_ctf?authSource=admin&replicaSet=atlas-zjxfcn-shard-0&retryWrites=true&w=majority&tls=true&appName=CTF
      JWT_SECRET: your_jwt_secret_here

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: cuhp-ctf-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    depends_on:
      - backend
